export const config = { runtime: 'edge' };

const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type',
};

function buildHtml(summary) {
  return `<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:40px 20px;background:#f8fafc;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">
<div style="max-width:480px;margin:0 auto;background:white;border:1px solid #e2e8f0;border-radius:8px;overflow:hidden;">

  <div style="background:#015650;padding:16px 24px;">
    <p style="margin:0 0 4px;font-size:12px;color:rgba(255,255,255,0.7);text-transform:uppercase;letter-spacing:0.05em;">SNAP Benefits Assistant</p>
    <p style="margin:0;font-size:22px;font-weight:600;color:white;line-height:1.4;">Your SNAP Eligibility Summary</p>
  </div>

  <div style="padding:24px;">
    <p style="margin:0 0 24px;font-size:14px;color:#1e293b;line-height:1.6;">
      Hi, based on what you shared, here's your eligibility summary.
      You can refer to this anytime you're ready to apply.
    </p>

    <table style="width:100%;border-collapse:collapse;margin-bottom:24px;">
      <tr style="border-bottom:1px solid #e2e8f0;">
        <td style="padding:12px 0;font-size:14px;color:#64748b;width:45%;">Status</td>
        <td style="padding:12px 0;font-size:14px;color:#24872e;font-weight:500;">${summary.status}</td>
      </tr>
      <tr style="border-bottom:1px solid #e2e8f0;">
        <td style="padding:12px 0;font-size:14px;color:#64748b;">Household size</td>
        <td style="padding:12px 0;font-size:14px;color:#1e293b;font-weight:500;">${summary.householdSize}</td>
      </tr>
      <tr style="border-bottom:1px solid #e2e8f0;">
        <td style="padding:12px 0;font-size:14px;color:#64748b;">Income limit</td>
        <td style="padding:12px 0;font-size:14px;color:#1e293b;font-weight:500;">${summary.incomeLimit}</td>
      </tr>
      <tr style="border-bottom:1px solid #e2e8f0;">
        <td style="padding:12px 0;font-size:14px;color:#64748b;">Exemption</td>
        <td style="padding:12px 0;font-size:14px;color:#1e293b;font-weight:500;">${summary.exemption}</td>
      </tr>
      <tr>
        <td style="padding:12px 0;font-size:14px;color:#64748b;">Potential benefit</td>
        <td style="padding:12px 0;font-size:16px;color:#1e827d;font-weight:600;">${summary.monthlyBenefit}</td>
      </tr>
    </table>

    <div style="background:#f0fdf8;border-radius:6px;padding:16px;margin-bottom:24px;">
      <p style="margin:0 0 8px;font-size:13px;font-weight:600;color:#1e827d;">Ready to apply?</p>
      <p style="margin:0 0 14px;font-size:13px;color:#1e293b;line-height:1.5;">
        Visit YourTexasBenefits.com to start your application. It takes about 30 minutes and you can save your progress.
      </p>
      <a href="https://yourtexasbenefits.com"
         style="display:inline-block;background:#1e827d;color:white;text-decoration:none;padding:12px 24px;border-radius:8px;font-size:13px;font-weight:500;">
        Start my application
      </a>
    </div>

    <div style="border-top:1px solid #e2e8f0;padding-top:16px;">
      <p style="margin:0;font-size:11px;color:#94a3b8;line-height:1.6;">
        This summary was generated by the SNAP Benefits Assistant for UT Austin students and community members.
        Your answers are not stored or shared beyond this email.
        If you have questions, visit
        <a href="https://deanofstudents.utexas.edu/emergency/utoutpost.php" style="color:#1e827d;text-decoration:none;">UT Outpost</a>
        for in-person advising.
      </p>
    </div>
  </div>

</div>
</body>
</html>`;
}

export default async function handler(req) {
  if (req.method === 'OPTIONS') {
    return new Response(null, { status: 204, headers: CORS });
  }

  if (req.method !== 'POST') {
    return new Response('Method not allowed', { status: 405, headers: CORS });
  }

  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) {
    return new Response(JSON.stringify({ error: 'Email service not configured' }), {
      status: 500,
      headers: { ...CORS, 'Content-Type': 'application/json' },
    });
  }

  let email, summary;
  try {
    ({ email, summary } = await req.json());
  } catch {
    return new Response(JSON.stringify({ error: 'Invalid request body' }), {
      status: 400,
      headers: { ...CORS, 'Content-Type': 'application/json' },
    });
  }

  if (!email || !summary) {
    return new Response(JSON.stringify({ error: 'Missing email or summary' }), {
      status: 400,
      headers: { ...CORS, 'Content-Type': 'application/json' },
    });
  }

  const resendRes = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      from: 'SNAP Benefits Assistant <onboarding@resend.dev>',
      to: [email],
      subject: 'Your SNAP Eligibility Summary',
      html: buildHtml(summary),
    }),
  });

  if (!resendRes.ok) {
    const errText = await resendRes.text();
    return new Response(JSON.stringify({ error: errText }), {
      status: resendRes.status,
      headers: { ...CORS, 'Content-Type': 'application/json' },
    });
  }

  return new Response(JSON.stringify({ ok: true }), {
    status: 200,
    headers: { ...CORS, 'Content-Type': 'application/json' },
  });
}
